### ISSUE TITLE
请问是使用bert-base-uncased还是bert-base-cased

### ISSUE THREAD

**Issue by z1ouhan** [zhengyima/knowqa#1]
因为提供的bert-config中"vocab_size": 30522，但是提示下载的https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models/bert-base-cased-pytorch_model.bin中"vocab_size": 28996。

**Comment by zhengyima** [comment]
我们使用的uncased哈，vocab_size是30522。

**Comment by z1ouhan** [comment]
感谢！还有想请问一下inference时的mode=2情况是没有开源吗，看代码好像没有

**Comment by zhengyima** [comment]
> 感谢！还有想请问一下inference时的mode=2情况是没有开源吗，看代码好像没有

刚刚更新了，之前不小心遗漏了。。
